import type { SectionSchema } from "@/lib/section-registry";

export const orderConfirmationContentSchema: SectionSchema = {
  name: "Confirmation de commande",
  type: "orderConfirmationContent",
  category: "checkout",
  description: "Page de confirmation de commande",
  icon: "CheckCircle2",
  settings: [
    { id: "content.title", type: "text", label: "Titre", default: "Commande confirmée !" },
    { id: "content.subtitle", type: "textarea", label: "Sous-titre", default: "Merci pour votre achat. Un email de confirmation a été envoyé." },
    { id: "content.orderNumberLabel", type: "text", label: "Label numéro", default: "Numéro de commande" },
    { id: "content.dateLabel", type: "text", label: "Label date", default: "Date" },
    { id: "content.totalLabel", type: "text", label: "Label total", default: "Total" },
    { id: "content.itemsLabel", type: "text", label: "Label articles", default: "Articles commandés" },
    { id: "content.trackingTitle", type: "text", label: "Titre suivi", default: "Suivi de commande" },
    { id: "content.receivedStatus", type: "text", label: "Statut reçu", default: "Commande reçue" },
    { id: "content.processingStatus", type: "text", label: "Statut préparation", default: "En préparation" },
    { id: "content.shippedStatus", type: "text", label: "Statut expédiée", default: "Expédiée" },
    { id: "content.deliveredStatus", type: "text", label: "Statut livrée", default: "Livrée" },
    { id: "content.homeButtonLabel", type: "text", label: "Bouton accueil", default: "Retour à l'accueil" },
    { id: "content.continueShoppingLabel", type: "text", label: "Bouton continuer", default: "Continuer les achats" },
    { id: "content.loadingMessage", type: "text", label: "Chargement", default: "Chargement de la commande..." },
    { id: "content.notFoundMessage", type: "text", label: "Introuvable", default: "Commande introuvable" },
    { id: "config.variant", type: "select", label: "Variant", options: [{ value: "default", label: "Default" }, { value: "minimal", label: "Minimal" }, { value: "detailed", label: "Detailed" }], default: "default" },
    { id: "config.showOrderDetails", type: "checkbox", label: "Afficher les détails", default: true },
    { id: "config.showTracking", type: "checkbox", label: "Afficher le suivi", default: true },
    { id: "config.showItemsList", type: "checkbox", label: "Afficher les articles", default: true },
    { id: "config.enableAnimations", type: "checkbox", label: "Animations", default: true },
    { id: "style.colors.background", type: "color", label: "Fond", default: "#ffffff" },
    { id: "style.colors.text", type: "color", label: "Texte", default: "#1a1a1a" },
    { id: "style.colors.accent", type: "color", label: "Accent", default: "#c9a96e" },
    { id: "style.colors.cardBg", type: "color", label: "Fond carte", default: "#f9fafb" },
    { id: "style.colors.border", type: "color", label: "Bordure", default: "#e5e7eb" },
    { id: "style.colors.success", type: "color", label: "Succès", default: "#22c55e" },
    { id: "style.spacing.paddingY", type: "number", label: "Padding vertical", default: 16, min: 0, max: 40 },
    {
      id: "style.spacing.container",
      type: "select",
      label: "Largeur",
      options: [
        { value: "full", label: "Pleine largeur" },
        { value: "contained", label: "Contenue" },
        { value: "narrow", label: "Étroit" },
      ],
      default: "narrow",
    },
  ],
  blocks: [],
  defaults: {
    content: {
      title: "Commande confirmée !",
      subtitle: "Merci pour votre achat. Un email de confirmation a été envoyé.",
      orderNumberLabel: "Numéro de commande",
      dateLabel: "Date",
      totalLabel: "Total",
      itemsLabel: "Articles commandés",
      trackingTitle: "Suivi de commande",
      receivedStatus: "Commande reçue",
      processingStatus: "En préparation",
      shippedStatus: "Expédiée",
      deliveredStatus: "Livrée",
      homeButtonLabel: "Retour à l'accueil",
      continueShoppingLabel: "Continuer les achats",
      loadingMessage: "Chargement de la commande...",
      notFoundMessage: "Commande introuvable",
    },
    config: {
      variant: "default",
      showOrderDetails: true,
      showTracking: true,
      showItemsList: true,
      enableAnimations: true,
    },
    style: {
      colors: {
        background: "#ffffff",
        text: "#1a1a1a",
        accent: "#c9a96e",
        cardBg: "#f9fafb",
        border: "#e5e7eb",
        success: "#22c55e",
      },
      spacing: {
        paddingY: "16",
        container: "narrow",
      },
    },
    classes: {},
  },
};

export default orderConfirmationContentSchema;
