import type { SectionSchema } from "@/lib/section-registry";

export const productDetailContentSchema: SectionSchema = {
  name: "Product Detail Content",
  type: "productDetailContent",
  category: "product",
  description: "Detail produit enrichi avec labels et options de page produit",
  icon: "ShoppingBag",
  settings: [
    { id: "content.product.name", type: "text", label: "Nom produit", default: "Produit Exemple" },
    { id: "content.product.price", type: "number", label: "Prix", default: 149 },
    { id: "content.product.oldPrice", type: "number", label: "Ancien prix", default: 199 },
    { id: "content.product.image", type: "image", label: "Image principale", default: "" },
    { id: "content.product.description", type: "textarea", label: "Description", default: "Description detaillee du produit." },
    { id: "content.product.badge", type: "text", label: "Badge", default: "Nouveau" },
    { id: "content.product.sku", type: "text", label: "SKU", default: "PROD-001" },
    { id: "content.addToCartLabel", type: "text", label: "Texte panier", default: "Ajouter au panier" },
    { id: "content.buyNowLabel", type: "text", label: "Texte achat immediat", default: "Acheter maintenant" },
    { id: "content.outOfStockLabel", type: "text", label: "Texte rupture", default: "Rupture de stock" },
    { id: "content.inStockLabel", type: "text", label: "Texte en stock", default: "En stock" },
    { id: "content.quantityLabel", type: "text", label: "Label quantite", default: "Quantite" },
    { id: "content.descriptionLabel", type: "text", label: "Label description", default: "Description" },
    { id: "content.specificationsLabel", type: "text", label: "Label specifications", default: "Specifications" },
    { id: "content.reviewsLabel", type: "text", label: "Label avis", default: "Avis clients" },
    { id: "content.shippingLabel", type: "text", label: "Label livraison", default: "Livraison" },
    { id: "content.returnsLabel", type: "text", label: "Label retours", default: "Retours" },
    { id: "content.shareLabel", type: "text", label: "Label partage", default: "Partager" },
    { id: "content.wishlistLabel", type: "text", label: "Label favoris", default: "Favoris" },
    { id: "content.relatedProductsTitle", type: "text", label: "Titre produits similaires", default: "Produits similaires" },
    { id: "content.freeShippingMessage", type: "text", label: "Message livraison gratuite", default: "Livraison gratuite disponible" },
    { id: "config.showReviews", type: "checkbox", label: "Afficher les avis", default: true },
    { id: "config.showSizeGuide", type: "checkbox", label: "Afficher guide des tailles", default: true },
    { id: "config.showShippingInfo", type: "checkbox", label: "Afficher infos livraison", default: true },
    { id: "config.showRelatedProducts", type: "checkbox", label: "Afficher produits similaires", default: true },
    { id: "config.enableWishlist", type: "checkbox", label: "Activer favoris", default: true },
    { id: "config.enableShare", type: "checkbox", label: "Activer partage", default: true },
    { id: "config.showQuantitySelector", type: "checkbox", label: "Afficher quantite", default: true },
    { id: "content.trustBadges.securePaymentLabel", type: "text", label: "Label paiement securise", default: "Paiement securise" },
    { id: "content.trustBadges.returnsLabel", type: "text", label: "Label retours", default: "Retours sous 30 jours" },
    { id: "content.breadcrumbLabel", type: "text", label: "Label fil dariane racine", default: "Produits" },
    { id: "content.shippingTabContent", type: "textarea", label: "Contenu onglet livraison", default: "Informations de livraison a completer selon les politiques de la boutique." },
    { id: "content.specsLabels.sku", type: "text", label: "Label SKU", default: "SKU" },
    { id: "content.specsLabels.category", type: "text", label: "Label categorie specs", default: "Categorie" },
    { id: "content.specsLabels.notAvailable", type: "text", label: "Label non disponible", default: "N/A" },
    { id: "content.noDescriptionLabel", type: "text", label: "Label pas de description", default: "Aucune description disponible." },
  ],
  blocks: [],
  defaults: {
    content: {
      product: {
        id: "1",
        name: "Produit Exemple",
        price: 149,
        oldPrice: 199,
        image:
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700&h=900&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700&h=900&fit=crop",
          "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=700&h=900&fit=crop",
        ],
        description: "Description detaillee du produit.",
        badge: "Nouveau",
        sku: "PROD-001",
        rating: 4.8,
        reviewCount: 42,
        category: "produits",
      },
      addToCartLabel: "Ajouter au panier",
      buyNowLabel: "Acheter maintenant",
      outOfStockLabel: "Rupture de stock",
      inStockLabel: "En stock",
      quantityLabel: "Quantite",
      descriptionLabel: "Description",
      specificationsLabel: "Specifications",
      reviewsLabel: "Avis clients",
      shippingLabel: "Livraison",
      returnsLabel: "Retours",
      shareLabel: "Partager",
      wishlistLabel: "Favoris",
      relatedProductsTitle: "Produits similaires",
      trustBadges: {
        securePaymentLabel: "Paiement securise",
        returnsLabel: "Retours sous 30 jours",
      },
      breadcrumbLabel: "Produits",
      shippingTabContent: "Informations de livraison a completer selon les politiques de la boutique.",
      specsLabels: {
        sku: "SKU",
        category: "Categorie",
        notAvailable: "N/A",
      },
      noDescriptionLabel: "Aucune description disponible.",
    },
    config: {
      showReviews: true,
      showSizeGuide: true,
      showShippingInfo: true,
      showRelatedProducts: true,
      enableWishlist: true,
      enableShare: true,
      showQuantitySelector: true,
      showBadges: true,
      showTrustBadges: true,
      showSpecsTab: true,
      showBreadcrumb: true,
    },
    style: {
      colors: {
        background: "white",
        text: "primary",
        accent: "accent",
        cardBg: "white",
        border: "#e5e5e5",
      },
      spacing: {
        paddingY: "12",
        container: "contained",
      },
    },
    classes: {},
  },
};

export default productDetailContentSchema;
