import type { SectionSchema } from "@/lib/section-registry";

export const productReviewsSchema: SectionSchema = {
  name: "Product Reviews",
  type: "productReviews",
  category: "product",
  description: "Bloc d'avis clients dynamique lie au produit affiche",
  icon: "MessageSquare",
  settings: [
    {
      id: "content.productId",
      type: "text",
      label: "ID produit",
      default: "",
    },
    {
      id: "content.title",
      type: "text",
      label: "Titre",
      default: "Avis clients",
    },
    {
      id: "content.subtitle",
      type: "textarea",
      label: "Sous-titre",
      default: "Consultez les retours clients et publiez votre propre avis.",
    },
    {
      id: "content.formTitle",
      type: "text",
      label: "Titre du formulaire",
      default: "Publier un avis",
    },
    {
      id: "content.formSubtitle",
      type: "textarea",
      label: "Sous-titre du formulaire",
      default: "Votre retour aide les autres clients a acheter sereinement.",
    },
    {
      id: "content.loginTitle",
      type: "text",
      label: "Titre connexion",
      default: "Connectez-vous pour publier un avis",
    },
    {
      id: "content.loginSubtitle",
      type: "textarea",
      label: "Sous-titre connexion",
      default: "Une session active est requise pour envoyer un commentaire.",
    },
    {
      id: "content.loginButtonLabel",
      type: "text",
      label: "Bouton connexion",
      default: "Se connecter",
    },
    {
      id: "content.emptyTitle",
      type: "text",
      label: "Titre vide",
      default: "Aucun avis pour le moment",
    },
    {
      id: "content.emptySubtitle",
      type: "textarea",
      label: "Sous-titre vide",
      default: "Soyez le premier a partager votre experience sur ce produit.",
    },
    {
      id: "content.ratingLabel",
      type: "text",
      label: "Label note",
      default: "Votre note",
    },
    {
      id: "content.commentLabel",
      type: "text",
      label: "Label commentaire",
      default: "Votre avis",
    },
    {
      id: "content.commentPlaceholder",
      type: "text",
      label: "Placeholder commentaire",
      default: "Racontez votre experience...",
    },
    {
      id: "content.formDisabledMessage",
      type: "text",
      label: "Message formulaire desactive",
      default: "La publication d'avis est desactivee pour cette section.",
    },
    {
      id: "content.linkProductTitle",
      type: "text",
      label: "Titre lier produit",
      default: "Lier a un produit",
    },
    {
      id: "content.linkProductSubtitle",
      type: "text",
      label: "Sous-titre lier produit",
      default: "Renseignez un identifiant produit UUID reel pour charger les avis et autoriser la publication.",
    },
    {
      id: "content.sessionCheckingLabel",
      type: "text",
      label: "Label verification session",
      default: "Verification de votre session client...",
    },
    {
      id: "content.accountBlockedTitle",
      type: "text",
      label: "Titre compte bloque",
      default: "Votre compte client boutique est bloque",
    },
    {
      id: "content.accountBlockedSubtitle",
      type: "text",
      label: "Sous-titre compte bloque",
      default: "Vous ne pouvez pas publier d'avis pour le moment.",
    },
    {
      id: "content.ratingOutOfLabel",
      type: "text",
      label: "Label note sur 5 (utiliser {rating})",
      default: "{rating}/5",
    },
    {
      id: "content.submitLabel",
      type: "text",
      label: "Bouton publication",
      default: "Publier l'avis",
    },
    {
      id: "config.showSummary",
      type: "checkbox",
      label: "Afficher le resume",
      default: true,
    },
    {
      id: "config.showForm",
      type: "checkbox",
      label: "Afficher le formulaire",
      default: true,
    },
    {
      id: "config.showVerifiedBadge",
      type: "checkbox",
      label: "Afficher badge verifie",
      default: true,
    },
    {
      id: "config.showAvatars",
      type: "checkbox",
      label: "Afficher les avatars",
      default: true,
    },
    {
      id: "config.layout",
      type: "select",
      label: "Disposition",
      options: [
        { value: "split", label: "Split" },
        { value: "stacked", label: "Empilee" },
      ],
      default: "split",
    },
    {
      id: "config.maxReviews",
      type: "number",
      label: "Nombre d'avis affiches",
      min: 1,
      max: 24,
      default: 6,
    },
  ],
  blocks: [],
  defaults: {
    content: {
      productId: "",
      title: "Avis clients",
      subtitle: "Consultez les retours clients et publiez votre propre avis.",
      formTitle: "Publier un avis",
      formSubtitle: "Votre retour aide les autres clients a acheter sereinement.",
      loginTitle: "Connectez-vous pour publier un avis",
      loginSubtitle: "Une session active est requise pour envoyer un commentaire.",
      loginButtonLabel: "Se connecter",
      emptyTitle: "Aucun avis pour le moment",
      emptySubtitle: "Soyez le premier a partager votre experience sur ce produit.",
      ratingLabel: "Votre note",
      commentLabel: "Votre avis",
      commentPlaceholder: "Racontez votre experience...",
      formDisabledMessage: "La publication d'avis est desactivee pour cette section.",
      linkProductTitle: "Lier a un produit",
      linkProductSubtitle: "Renseignez un identifiant produit UUID reel pour charger les avis et autoriser la publication.",
      sessionCheckingLabel: "Verification de votre session client...",
      accountBlockedTitle: "Votre compte client boutique est bloque",
      accountBlockedSubtitle: "Vous ne pouvez pas publier d'avis pour le moment.",
      ratingOutOfLabel: "{rating}/5",
      submitLabel: "Publier l'avis",
    },
    config: {
      showSummary: true,
      showForm: true,
      showVerifiedBadge: true,
      showAvatars: true,
      layout: "split",
      maxReviews: 6,
    },
    style: {
      colors: {
        background: "white",
        text: "primary",
        accent: "accent",
        cardBg: "white",
        border: "#e5e5e5",
      },
      spacing: {
        paddingY: "16",
        container: "contained",
        gap: "6",
      },
    },
    classes: {},
  },
};

export default productReviewsSchema;
