import type { SectionSchema } from "@/lib/section-registry";

export const registerSchema: SectionSchema = {
  name: "Register",
  type: "register",
  category: "auth",
  description: "Formulaire de creation de compte client",
  icon: "Shield",
  settings: [
    { id: "content.title", type: "text", label: "Titre", default: "Creer un compte" },
    {
      id: "content.subtitle",
      type: "textarea",
      label: "Sous-titre",
      default: "Rejoignez notre communaute",
    },
    { id: "content.firstNameLabel", type: "text", label: "Label prenom", default: "Prenom" },
    { id: "content.firstNamePlaceholder", type: "text", label: "Placeholder prenom", default: "Jean" },
    { id: "content.lastNameLabel", type: "text", label: "Label nom", default: "Nom" },
    { id: "content.lastNamePlaceholder", type: "text", label: "Placeholder nom", default: "Dupont" },
    { id: "content.emailLabel", type: "text", label: "Label email", default: "Adresse email" },
    { id: "content.emailPlaceholder", type: "text", label: "Placeholder email", default: "vous@exemple.com" },
    { id: "content.phoneLabel", type: "text", label: "Label telephone", default: "Telephone" },
    { id: "content.phonePlaceholder", type: "text", label: "Placeholder telephone", default: "+509..." },
    { id: "content.passwordLabel", type: "text", label: "Label mot de passe", default: "Mot de passe" },
    { id: "content.passwordPlaceholder", type: "text", label: "Placeholder mot de passe", default: "••••••••" },
    { id: "content.passwordConfirmLabel", type: "text", label: "Label confirmation", default: "Confirmer le mot de passe" },
    { id: "content.passwordConfirmPlaceholder", type: "text", label: "Placeholder confirmation", default: "••••••••" },
    { id: "content.termsLabel", type: "text", label: "Label conditions", default: "J'accepte les conditions d'utilisation" },
    { id: "content.newsletterLabel", type: "text", label: "Label newsletter", default: "Je souhaite recevoir la newsletter" },
    { id: "content.submitButtonText", type: "text", label: "Texte bouton", default: "Creer mon compte" },
    { id: "content.loadingText", type: "text", label: "Texte chargement", default: "Creation..." },
    { id: "content.socialLoginDivider", type: "text", label: "Separateur social", default: "Ou avec email" },
    { id: "content.hasAccountText", type: "text", label: "Texte deja compte", default: "Deja un compte?" },
    { id: "content.loginLinkText", type: "text", label: "Texte lien connexion", default: "Se connecter" },
    {
      id: "config.variant",
      type: "select",
      label: "Variant",
      options: [
        { value: "centered", label: "Centered" },
        { value: "split", label: "Split" },
        { value: "minimal", label: "Minimal" },
      ],
      default: "centered",
    },
    { id: "config.showFirstName", type: "checkbox", label: "Afficher prenom", default: true },
    { id: "config.showLastName", type: "checkbox", label: "Afficher nom", default: true },
    { id: "config.showEmail", type: "checkbox", label: "Afficher email", default: true },
    { id: "config.showPhone", type: "checkbox", label: "Afficher telephone", default: true },
    { id: "config.showPassword", type: "checkbox", label: "Afficher mot de passe", default: true },
    { id: "config.showPasswordConfirm", type: "checkbox", label: "Afficher confirmation", default: true },
    { id: "config.showTerms", type: "checkbox", label: "Afficher conditions", default: true },
    { id: "config.showNewsletter", type: "checkbox", label: "Afficher newsletter", default: true },
    { id: "config.showSocialLogin", type: "checkbox", label: "Afficher social login", default: true },
    { id: "config.requireTerms", type: "checkbox", label: "Conditions obligatoires", default: true },
  ],
  blocks: [],
  defaults: {
    content: {
      title: "Creer un compte",
      subtitle: "Rejoignez notre communaute",
      firstNameLabel: "Prenom",
      firstNamePlaceholder: "Jean",
      lastNameLabel: "Nom",
      lastNamePlaceholder: "Dupont",
      emailLabel: "Adresse email",
      emailPlaceholder: "vous@exemple.com",
      phoneLabel: "Telephone",
      phonePlaceholder: "+509...",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "••••••••",
      passwordConfirmLabel: "Confirmer le mot de passe",
      passwordConfirmPlaceholder: "••••••••",
      termsLabel: "J'accepte les conditions d'utilisation",
      newsletterLabel: "Je souhaite recevoir la newsletter",
      submitButtonText: "Creer mon compte",
      loadingText: "Creation...",
      socialLoginDivider: "Ou avec email",
      hasAccountText: "Deja un compte?",
      loginLinkText: "Se connecter",
    },
    config: {
      variant: "centered",
      showFirstName: true,
      showLastName: true,
      showEmail: true,
      showPhone: true,
      showPassword: true,
      showPasswordConfirm: true,
      showTerms: true,
      showNewsletter: true,
      showSocialLogin: true,
      socialProviders: ["google", "facebook", "apple"],
      requireTerms: true,
    },
    style: {
      colors: {
        background: "white",
        cardBackground: "white",
        text: "primary",
        accent: "accent",
      },
      spacing: {
        paddingY: "16",
        container: "contained",
      },
    },
    classes: {},
  },
};

export default registerSchema;
