import type { SectionSchema } from "@/lib/section-registry";

export const checkoutContentSchema: SectionSchema = {
  name: "Checkout avancé",
  type: "checkoutContent",
  category: "checkout",
  description: "Processus de commande complet avec récapitulatif",
  icon: "ShoppingBag",
  settings: [
    { id: "title", type: "text", label: "Titre", default: "Commande" },
    { id: "subtitle", type: "textarea", label: "Sous-titre", default: "" },
    {
      id: "stepLabels",
      type: "textarea",
      label: "Labels des étapes",
      default: "Livraison\nPaiement\nConfirmation",
      info: "Une ligne par étape.",
    },
    { id: "content.backToCartLabel", type: "text", label: "Retour panier", default: "Retour au panier" },
    { id: "content.deliveryStepTitle", type: "text", label: "Étape livraison", default: "Livraison" },
    { id: "content.paymentStepTitle", type: "text", label: "Étape paiement", default: "Paiement" },
    { id: "content.reviewStepTitle", type: "text", label: "Étape confirmation", default: "Confirmation" },
    { id: "content.placeOrderLabel", type: "text", label: "Confirmer la commande", default: "Confirmer la commande" },
    { id: "content.processingLabel", type: "text", label: "Traitement", default: "Traitement..." },
    { id: "content.orderSummaryLabel", type: "text", label: "Résumé commande", default: "Résumé de la commande" },
    { id: "content.subtotalLabel", type: "text", label: "Sous-total", default: "Sous-total" },
    { id: "content.shippingLabel", type: "text", label: "Livraison", default: "Livraison" },
    { id: "content.totalLabel", type: "text", label: "Total", default: "Total" },
    { id: "content.notesPlaceholder", type: "textarea", label: "Placeholder notes", default: "Notes supplémentaires..." },
    { id: "content.securePaymentText", type: "text", label: "Paiement sécurisé", default: "Paiement sécurisé" },
    { id: "config.variant", type: "select", label: "Variant", options: [{ value: "default", label: "Default" }, { value: "minimal", label: "Minimal" }, { value: "split", label: "Split" }], default: "default" },
    { id: "config.showSteps", type: "checkbox", label: "Afficher les étapes", default: true },
    { id: "config.showOrderSummary", type: "checkbox", label: "Afficher le résumé", default: true },
    { id: "config.showSecurePayment", type: "checkbox", label: "Afficher le badge sécurisé", default: true },
    { id: "config.enableNotes", type: "checkbox", label: "Autoriser les notes", default: true },
    { id: "style.colors.background", type: "color", label: "Fond", default: "#ffffff" },
    { id: "style.colors.text", type: "color", label: "Texte", default: "#1a1a1a" },
    { id: "style.colors.accent", type: "color", label: "Accent", default: "#c9a96e" },
    { id: "style.colors.cardBg", type: "color", label: "Fond carte", default: "#ffffff" },
    { id: "style.colors.border", type: "color", label: "Bordure", default: "#e5e7eb" },
    { id: "style.spacing.paddingY", type: "number", label: "Padding vertical", default: 16, min: 0, max: 40 },
    {
      id: "style.spacing.container",
      type: "select",
      label: "Largeur",
      options: [
        { value: "full", label: "Pleine largeur" },
        { value: "contained", label: "Contenue" },
        { value: "narrow", label: "Étroit" },
      ],
      default: "contained",
    },
  ],
  blocks: [],
  defaults: {
    title: "Commande",
    subtitle: "",
    stepLabels: "Livraison\nPaiement\nConfirmation",
    content: {
      backToCartLabel: "Retour au panier",
      deliveryStepTitle: "Livraison",
      paymentStepTitle: "Paiement",
      reviewStepTitle: "Confirmation",
      placeOrderLabel: "Confirmer la commande",
      processingLabel: "Traitement...",
      orderSummaryLabel: "Résumé de la commande",
      subtotalLabel: "Sous-total",
      shippingLabel: "Livraison",
      totalLabel: "Total",
      notesPlaceholder: "Notes supplémentaires...",
      securePaymentText: "Paiement sécurisé",
    },
    config: {
      variant: "default",
      showSteps: true,
      showOrderSummary: true,
      showSecurePayment: true,
      enableNotes: true,
    },
    style: {
      colors: {
        background: "#ffffff",
        text: "#1a1a1a",
        accent: "#c9a96e",
        cardBg: "#ffffff",
        border: "#e5e7eb",
      },
      spacing: {
        paddingY: "16",
        container: "contained",
      },
    },
    classes: {},
  },
};

export default checkoutContentSchema;
