import type { SectionSchema } from "@/lib/section-registry";

export const cartSchema: SectionSchema = {
  name: "Cart",
  type: "cart",
  category: "cart",
  description: "Panier configurable avec options de paiement et livraison",
  icon: "ShoppingCart",
  settings: [
    { id: "content.title", type: "text", label: "Titre", default: "Mon Panier" },
    { id: "content.emptyMessage", type: "textarea", label: "Message panier vide", default: "Votre panier est vide." },
    { id: "content.subtotalLabel", type: "text", label: "Label sous-total", default: "Sous-total" },
    { id: "content.shippingLabel", type: "text", label: "Label livraison", default: "Livraison" },
    { id: "content.totalLabel", type: "text", label: "Label total", default: "Total" },
    { id: "content.checkoutLabel", type: "text", label: "Label checkout", default: "Passer la commande" },
    { id: "content.continueShoppingLabel", type: "text", label: "Continuer achats", default: "Continuer les achats" },
    { id: "content.clearCartLabel", type: "text", label: "Vider panier", default: "Vider le panier" },
    { id: "content.couponPlaceholder", type: "text", label: "Placeholder coupon", default: "Code promo" },
    { id: "content.securePaymentText", type: "text", label: "Texte paiement sécurisé", default: "Paiement sécurisé" },
    { id: "content.freeShippingMessage", type: "text", label: "Message livraison gratuite", default: "" },
    { id: "content.deliveryModeLabel", type: "text", label: "Label livraison", default: "Livraison" },
    { id: "content.pickupModeLabel", type: "text", label: "Label retrait", default: "Retrait" },
    { id: "content.addAddressLabel", type: "text", label: "Ajouter adresse", default: "Ajouter une adresse" },
    { id: "content.loginRequiredMessage", type: "textarea", label: "Connexion requise", default: "Connectez-vous pour continuer." },
    {
      id: "config.variant",
      type: "select",
      label: "Variant",
      options: [
        { value: "default", label: "Default" },
        { value: "minimal", label: "Minimal" },
        { value: "split", label: "Split" },
      ],
      default: "default",
    },
    { id: "config.showCouponField", type: "checkbox", label: "Afficher coupon", default: true },
    {
      id: "config.showShippingCalculator",
      type: "checkbox",
      label: "Afficher calcul livraison",
      default: true,
    },
    { id: "config.showSecurePayment", type: "checkbox", label: "Afficher paiement sécurisé", default: true },
    { id: "config.enableClearCart", type: "checkbox", label: "Vider panier", default: true },
    {
      id: "config.showDeliveryModeSelector",
      type: "checkbox",
      label: "Sélecteur mode livraison",
      default: true,
    },
    { id: "style.colors.background", type: "text", label: "Fond", default: "white" },
    { id: "style.colors.text", type: "text", label: "Texte", default: "primary" },
    { id: "style.colors.accent", type: "text", label: "Accent", default: "accent" },
    { id: "style.colors.cardBg", type: "text", label: "Fond carte", default: "#ffffff" },
    { id: "style.colors.border", type: "text", label: "Bordure", default: "#e5e5e5" },
    { id: "style.spacing.paddingY", type: "text", label: "Padding Y", default: "10" },
    {
      id: "style.spacing.container",
      type: "select",
      label: "Container",
      options: [
        { value: "full", label: "Full" },
        { value: "contained", label: "Contained" },
        { value: "narrow", label: "Narrow" },
      ],
      default: "contained",
    },
  ],
  defaults: {
    content: {
      title: "Mon Panier",
      emptyMessage: "Votre panier est vide.",
      subtotalLabel: "Sous-total",
      shippingLabel: "Livraison",
      totalLabel: "Total",
      checkoutLabel: "Passer la commande",
      continueShoppingLabel: "Continuer les achats",
      clearCartLabel: "Vider le panier",
      couponPlaceholder: "Code promo",
      securePaymentText: "Paiement sécurisé",
      freeShippingMessage: "",
      deliveryModeLabel: "Livraison",
      pickupModeLabel: "Retrait",
      addAddressLabel: "Ajouter une adresse",
      loginRequiredMessage: "Connectez-vous pour continuer.",
    },
    config: {
      variant: "default",
      showCouponField: true,
      showShippingCalculator: true,
      showSecurePayment: true,
      enableClearCart: true,
      showDeliveryModeSelector: true,
    },
    style: {
      colors: {
        background: "white",
        text: "primary",
        accent: "accent",
        cardBg: "#ffffff",
        border: "#e5e5e5",
      },
      spacing: {
        paddingY: "10",
        container: "contained",
      },
    },
  },
};

export default cartSchema;
