import type { SectionSchema } from "@/lib/section-registry";

export const accountDashboardSchema: SectionSchema = {
  name: "Compte client",
  type: "accountDashboard",
  category: "account",
  description: "Tableau de bord client avec commandes, adresses et profil",
  icon: "UserRound",
  settings: [
    { id: "content.title", type: "text", label: "Titre", default: "Mon Compte" },
    {
      id: "content.subtitle",
      type: "textarea",
      label: "Sous-titre",
      default: "Gerez vos informations et vos commandes",
    },
    { id: "content.welcomeMessage", type: "text", label: "Message d'accueil", default: "Bonjour" },
    { id: "content.memberSinceLabel", type: "text", label: "Libellé date adhésion", default: "Membre depuis" },
    { id: "content.ordersLabel", type: "text", label: "Libellé commandes", default: "Commandes" },
    { id: "content.inProgressLabel", type: "text", label: "Libellé commandes en cours", default: "En cours" },
    { id: "content.addressesLabel", type: "text", label: "Libellé adresses", default: "Adresses" },
    { id: "content.loyaltyPointsLabel", type: "text", label: "Libellé points", default: "Points fidélité" },
    { id: "content.noOrdersMessage", type: "textarea", label: "Message sans commande", default: "Aucune commande pour le moment." },
    { id: "content.addAddressLabel", type: "text", label: "Ajouter une adresse", default: "Ajouter une adresse" },
    { id: "content.defaultAddressLabel", type: "text", label: "Adresse par défaut", default: "Par défaut" },
    { id: "content.editLabel", type: "text", label: "Libellé modifier", default: "Modifier" },
    { id: "content.deleteLabel", type: "text", label: "Libellé supprimer", default: "Supprimer" },
    { id: "content.logoutLabel", type: "text", label: "Libellé déconnexion", default: "Déconnexion" },
    { id: "content.saveLabel", type: "text", label: "Libellé enregistrer", default: "Enregistrer" },
    { id: "content.cancelLabel", type: "text", label: "Libellé annuler", default: "Annuler" },
    { id: "content.loginTitle", type: "text", label: "Titre connexion", default: "Connectez-vous" },
    {
      id: "content.loginSubtitle",
      type: "textarea",
      label: "Sous-titre connexion",
      default: "Connectez-vous ou créez un compte pour accéder à votre espace client.",
    },
    { id: "content.loginButtonLabel", type: "text", label: "Bouton connexion", default: "Connexion" },
    { id: "content.registerButtonLabel", type: "text", label: "Bouton inscription", default: "Inscription" },
    {
      id: "config.variant",
      type: "select",
      label: "Mise en page",
      options: [
        { value: "sidebar", label: "Sidebar" },
        { value: "tabs", label: "Tabs" },
        { value: "minimal", label: "Minimal" },
      ],
      default: "sidebar",
    },
    { id: "config.showStats", type: "checkbox", label: "Afficher les statistiques", default: true },
    { id: "config.showOrders", type: "checkbox", label: "Afficher les commandes", default: true },
    { id: "config.showAddresses", type: "checkbox", label: "Afficher les adresses", default: true },
    { id: "config.showProfile", type: "checkbox", label: "Afficher le profil", default: true },
    { id: "config.showLogout", type: "checkbox", label: "Afficher la déconnexion", default: true },
    { id: "config.enableAccountDelete", type: "checkbox", label: "Autoriser la suppression", default: true },
    { id: "style.colors.background", type: "color", label: "Fond", default: "#f8fafc" },
    { id: "style.colors.text", type: "color", label: "Texte", default: "#1e293b" },
    { id: "style.colors.accent", type: "color", label: "Accent", default: "#c9a96e" },
    { id: "style.colors.cardBg", type: "color", label: "Fond carte", default: "#ffffff" },
    { id: "style.colors.border", type: "color", label: "Bordure", default: "#e5e7eb" },
    {
      id: "style.spacing.container",
      type: "select",
      label: "Largeur",
      options: [
        { value: "full", label: "Pleine largeur" },
        { value: "contained", label: "Contenue" },
        { value: "narrow", label: "Étroit" },
      ],
      default: "contained",
    },
    { id: "style.spacing.paddingY", type: "number", label: "Padding vertical", default: 12, min: 0, max: 40 },
  ],
  blocks: [],
  defaults: {
    content: {
      title: "Mon Compte",
      subtitle: "Gerez vos informations et vos commandes",
      welcomeMessage: "Bonjour",
      memberSinceLabel: "Membre depuis",
      ordersLabel: "Commandes",
      inProgressLabel: "En cours",
      addressesLabel: "Adresses",
      loyaltyPointsLabel: "Points fidélité",
      noOrdersMessage: "Aucune commande pour le moment.",
      addAddressLabel: "Ajouter une adresse",
      defaultAddressLabel: "Par défaut",
      editLabel: "Modifier",
      deleteLabel: "Supprimer",
      logoutLabel: "Déconnexion",
      saveLabel: "Enregistrer",
      cancelLabel: "Annuler",
      loginTitle: "Connectez-vous",
      loginSubtitle: "Connectez-vous ou créez un compte pour accéder à votre espace client.",
      loginButtonLabel: "Connexion",
      registerButtonLabel: "Inscription",
    },
    config: {
      variant: "sidebar",
      showStats: true,
      showOrders: true,
      showAddresses: true,
      showProfile: true,
      showLogout: true,
      enableAccountDelete: true,
    },
    style: {
      colors: {
        background: "#f8fafc",
        text: "#1e293b",
        accent: "#c9a96e",
        cardBg: "#ffffff",
        border: "#e5e7eb",
      },
      spacing: {
        container: "contained",
        paddingY: "12",
      },
    },
    classes: {},
  },
};

export default accountDashboardSchema;
